### ISSUE TITLE
How to reverse the values of the axis

### ISSUE THREAD

**Issue by jguo83** [ms609/Ternary#20]
Hi Martin,

The ternary package is super easy to use for me, a beginner of R programming. And I'm stuck in one problem.

I want to reverse the values of the axis, for example, the axis I got right now is from 100 to 0 from the top to the left bottom, how can I change it from 0 to 100 from the top to the left bottom? (The same for the other two axis)

Thanks a lot!!

**Comment by ms609** [comment]
Hi @jguo83 ,

Glad to hear that you are getting on well with the package.

I'm afraid that I'm not sure that I completely understand your question.  I can't envision how a ternary plot would work if "100" was at the opposite side of the triangle from the relevant corner.

If you just want to change the labelling, you can use 

` TernaryPlot(axis.labels=seq(100, 0, by=-10))`

If you want to change the orientation of the triangle, try

`TernaryPlot(point='down')`

If you want to change the position of the axis labels (so that horizontal lines are labelled on the right hand side of an upwards-pointing plot rather than the left), then this isn't currently possible, and I'd be interested to hear more about the use case that makes this necessary -- it would be feasible to implement in a future release, but would take quite a bit of work.

**Comment by jguo83** [comment]
> Hi @jguo83 ,
> 
> Glad to hear that you are getting on well with the package.
> 
> I'm afraid that I'm not sure that I completely understand your question. I can't envision how a ternary plot would work if "100" was at the opposite side of the triangle from the relevant corner.
> 
> If you just want to change the labelling, you can use
> 
> ` TernaryPlot(axis.labels=seq(100, 0, by=-10))`
> 
> If you want to change the orientation of the triangle, try
> 
> `TernaryPlot(point='down')`
> 
> If you want to change the position of the axis labels (so that horizontal lines are labelled on the right hand side of an upwards-pointing plot rather than the left), then this isn't currently possible, and I'd be interested to hear more about the use case that makes this necessary -- it would be feasible to implement in a future release, but would take quite a bit of work.

**Comment by jguo83** [comment]
Hi Martin,

Thanks you very much for your quick reply!

Yes, I want to change the labelling, it's very helpful, thanks a lot!!

(I'm a beginner of the GitHub, sorry for accidentally closed the issue
without any replying... hope you can read this one.

Good luck!
