### ISSUE TITLE
Suggestion: multiple scales

### ISSUE THREAD

**Issue by lsw5077** [ms609/Ternary#51]
Hi! I'm using Ternary to make plots of different fish phenotypes. It would be really useful to me if the different sides of the plot could have different scales reflecting the different scales of the traits I'm working with. For example, the code 

TernaryPlot(axis.labels = c(seq(0, 10, by = 1),
                            seq(0, 100, by = 10),
                            seq(0, 50, by = 5)))

would yield a plot that goes from 0-10 on one side, 0-100 on the second, and 0-50 on the third. Thanks for building the package. I'm really enjoying it so far!

**Comment by kamapu** [comment]
I was almost to post my own issue on this regard. I also support the request of @lsw5077 enabling customized ranges for the three axes. I also agree about the usefulness of this package.

**Comment by kamapu** [comment]
Oh! I found one argument against this desire (I was thinking about three independent variables). I realized when the three plotted variables are not complementary (the sum of the three values should be 100) it won't properly work. Thus, the only possible alternative is to use fractions (all scales from 0 to 1) instead of percentages.

**Comment by ms609** [comment]
Hi, thanks for the suggestions; as @kamapu notes, it's not clear how a ternary plot might work when the plotted variables are not complementary.  @lsw5077 , are you able to provide a simple example so I can understand what data would be plotted and how this would work in practice?

**Comment by ms609** [comment]
I'm closing this issue because I'm not clear exactly how this would work.  (Perhaps you had in mind something akin to a [Holdridge plot](https://ms609.github.io/Ternary/dev/articles/Holdridge.html)?)
Please do re-open the issue if you are able to describe in a little more detail the behaviour you require.
