### ISSUE TITLE
Cannot start Ternary shiny app

### ISSUE THREAD

**Issue by psb1618** [ms609/Ternary#56]
In Windows 10 (fully updated), with the current version of R, the command...
Ternary::TernaryApp()
... restults in the following error message:
"Error: Could not find example directory. Try re-installing 'Ternary'."
Please, advise!
(Note: Ternary has been installed and re-installed without errors message.)

**Comment by ms609** [comment]
Thanks for the report and sorry for the inconvenience!

Did you install Ternary from CRAN, or from Github?  If the latter, try reinstalling with
`devtools::install_github("ms609/Ternary", args="--recursive")`

Does the R command `system.file('TernaryApp', package = 'Ternary')` return a path on your computer? If so, could you navigate to this folder: is it empty?

**Comment by psb1618** [comment]
Ternary was installed two ways, neither of which solved the problem: from CRAN, and by downloading the ZIP from Github and installing the package manually. (Typing devtools::... returns various error messages saying that developer tools and whatnot need to be installed, and that led me to a rabbit hole of increasing demands to install more and more programming tools for R package developers.) The Ternary package is showing up in the library directory. The R command system.file... did not return a path on the computer. Please advise!

**Comment by ms609** [comment]
Thanks. This information has helped me to diagnose the problem (I think!).  The immediate workaround is to install git and the development tools (sorry, I know that's a headache!).  

Meanwhile, I'll prepare a fix to push to CRAN once the server re-opens for submissions this week.  Sorry for the inconvenience!

**Comment by ms609** [comment]
Fixed in v2.0.0, now submitted to CRAN.

In the meantime, to install the app locally, after downloading the latest ZIP from GitHub, download https://github.com/ms609/TernaryApp/archive/refs/heads/master.zip and unzip its contents to the location given by `system.file("TernaryApp", package = "Ternary")`.

If the files aren't available locally, `TernaryApp()` will nwo run `shiny::runGitHub("ms609/TernaryApp")` to download and launch the app directly from the relevant GitHub server.
